apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ infrastructure_id }} 
  name: {{ infrastructure_id }}-{{ role }}-{{ region }}{{ zone }} 
  namespace: openshift-machine-api
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ infrastructure_id }} 
      machine.openshift.io/cluster-api-machineset: {{ infrastructure_id }}-{{ role }}-{{ region }}{{ zone }} 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ infrastructure_id }} 
        machine.openshift.io/cluster-api-machine-role: {{ role }} 
        machine.openshift.io/cluster-api-machine-type: {{ role }} 
        machine.openshift.io/cluster-api-machineset: {{ infrastructure_id }}-{{ role }}-{{ region }}{{ zone }} 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/{{ role }}: "" 
      providerSpec:
        value:
          ami:
            id: {{ ami_id }} 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: {{ hdd_size | default(mset_default_hdd_size) }}
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ infrastructure_id }}-worker-profile 
          instanceType: {{ instance_type | default (mset_default_instance_type )}}
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ region }}{{ zone }}
            region: {{ region }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ infrastructure_id }}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ infrastructure_id }}-private-{{ region }}{{ zone }}
          tags:
            - name: kubernetes.io/cluster/{{ infrastructure_id }} 
              value: owned
          userDataSecret:
            name: worker-user-data


