---
- name: Create namespaces and Operator Groups
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'rhocs-ns.yaml') }}"
- name: Create Subscription
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'rhocs-sub.yaml') }}"
