---
# tasks file for ocp_rhocs
#- import_role:
#    name: ocp_infra
#  vars:
#    infra_role: "{{rhocs_role}}"
#
- import_tasks: install.yaml
  tags: install

- import_tasks: storage_cluster.yaml
  tags: create_scluster
