- name: find nodes to run RHOCS on
  k8s_info: 
    kubeconfig: "{{ kubeconfig }}"
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/rhocs= 
  when: rhocs_nodes | default([])| length==0 
  register: target_nodes

- name: Create list of nodes to run RHOCS on
  set_fact:
     rhocs_nodes: "{{ target_nodes.resources | map (attribute='metadata')| list | map(attribute='name') | list }}" 


- name: Debug nodes
  debug:
    var: rhocs_nodes

- name: Add label to nodes
  k8s: 
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ item }}"    
        labels:
          cluster.ocs.openshift.io/openshift-storage: ""  
  with_items: "{{ rhocs_nodes }}"

- name: Create Storage Cluster
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'rhocs-scluster.yaml') }}"
