---
# Create new role for RHOCS
- hosts: bastion-ocp
  vars:
    rhocs_role: rhocs
    msets:
    - replicas: 1
      role: "{{ rhocs_role }}"
      instance_type: m4.4xlarge
    mset_user_data_secret: "{{rhocs_role}}-user-data"
    move_ingress: "false"
    infra_role: "{{rhocs_role}}"
  roles: 
  - ocp_infra
  - ocp_mset
  - ocp_rhocs
