---
- hosts: bastion-ocp
  vars: 
   htpasswd:
    - admin: "{{ lookup('password', './admin_passwordfile length=24 ') }}"
    - developer: R3dH4t!!
   admin_users:
    - admin
  roles: 
    - ocp_auth
