---
- name: create local container
  hosts: localhost
  tasks:
    - name: make sure the local image exists
      podman_image_info:
        name: "{{ local_container_image_name  }}"
      register: local_container_image
    - debug: 
        var: local_container_image
    - debug:
        msg: "The condition: {{(local_container_image.images | length > 0)}}"
    - name: build the image
      command: buildah bud --tag {{ local_container_image_name }} -f Dockerfile local_container
      when: "{{(local_container_image.images | length == 0)}}"

      
