---
- name: Create Namespaces
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
  - oor-namespace.yaml
- name: Create Jaeger Operator Group
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'oor-og.yaml') }}"
- name: Get available Jaeger channels
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    name: "jaeger-product"
    kind: "PackageManifest"
    namespace: "openshift-marketplace"
  register: jaeger_manifest
  when: jaeger_channel is not defined
- name: set local var
  set_fact:
     jaeger_channel: "{{ jaeger_manifest.resources[0].status.defaultChannel }}"
  when: jaeger_channel is not defined
- name: Subscribing on channel {{ jaeger_channel }}
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'jaeger-sub.yaml') }}"
