---
- name: Create Namespaces
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
  - oor-namespace.yaml
- name: Create Kiali Operator Group
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'oor-og.yaml') }}"
- name: Get available Kiali channels
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    name: "kiali-ossm"
    kind: "PackageManifest"
    namespace: "openshift-marketplace"
  register: kiali_manifest
  when: kiali_channel is not defined
- name: set local var
  set_fact:
     kiali_channel: "{{ kiali_manifest.resources[0].status.defaultChannel }}"
  when: kiali_channel is not defined
- name: Subscribing on channel {{ kiali_channel }}
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'kiali-sub.yaml') }}"
