---
# tasks file for ocp_infra
- import_tasks: machineconfig.yml
  tags: machine_config
- import_tasks: user-data-secret.yml
  tags: user-data-secret
- import_tasks: router-config.yml
  tags: move-ingress
  when: "{{ move_ingress is 'true' }}"
