---
- name: Get current worker user data secret
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Secret
    namespace: openshift-machine-api
    name: worker-user-data 
  register: wud

- name: Get userdata content
  set_fact:
    ud_content: "{{ wud.resources[0].data.userData }}"

- name: Modified Secret userData
  debug:
    var: ud_content | b64decode | regex_replace('config/worker',"config/{{ infra_role }}")

- name: Create Infra user data secret
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    kind: Secret
    name: "{{ infra_role }}-user-data"
    namespace: openshift-machine-api
    resource_definition:
       type: Opaque
       data:
         disableTemplating: "{{ wud.resources[0].data.disableTemplating }}"
         userData: "{{ ud_content | b64decode | regex_replace('config/worker','config/'+infra_role)| b64encode }}"

