---
- name: Create Namespaces
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
  - clo-namespace.yaml
- name: Create CLO-OperatorGroup 
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'clo-og.yaml') }}"
- name: Get available CLO channels
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    name: "cluster-logging"
    kind: "PackageManifest"
    namespace: "openshift-marketplace"
  register: clo_manifest
  when: clo_channel is not defined
- name: set local var
  set_fact:
     clo_channel: "{{ clo_manifest.resources[0].status.defaultChannel }}"
  when: clo_channel is not defined
- name: Create CLO-Subscription on channel {{ clo_channel }}
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'clo-sub.yaml') }}"
