---
- name: Create Namespaces
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items:
  - eo-namespace.yaml
- name: Create ES Operator Group
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'eo-og.yaml') }}"
- name: Get available ES channels
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    name: "elasticsearch-operator"
    kind: "PackageManifest"
    namespace: "openshift-marketplace"
  register: es_manifest
  when: es_channel is not defined
- name: set local var
  set_fact:
     es_channel: "{{ es_manifest.resources[0].status.defaultChannel }}"
  when: es_channel is not defined
- name: Subscribing on channel {{ es_channel }}
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'eo-sub.yaml') }}"
- name: Create RBAC
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'eo-rbac.yaml') }}"
