---
# tasks file for ocp_clo
- import_tasks: es.yml
  tags: install
- import_tasks: clo.yml
  tags: install
# Wait a little to make sure operator is up
- name: Wait for operator
  k8s_info: 
    api_version: operators.coreos.com/v1alpha1
    kubeconfig: "{{ kubeconfig }}"
    kind: Subscription
    name: cluster-logging
    namespace: openshift-logging
  register: clo_sub
  retries: 30
  delay: 5
  until: clo_sub.resources[0] is defined and clo_sub.resources[0].status is defined and clo_sub.resources[0].status.state is defined and clo_sub.resources[0].status.state == 'AtLatestKnown'
- import_tasks: setup.yml
  tags: setup
