---
# tasks file for ocp_clo
- import_tasks: install.yml
  tags: install
# Wait a little to make sure operator is up
- name: Wait for operator
  pause:
    seconds: 5
- import_tasks: setup.yml
  tags: setup
