apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "kiali-{{ kiali_channel }}"
  namespace: "openshift-operators-redhat" 
spec:
  channel: "{{ kiali_channel | quote }}"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "kiali-ossm"
