apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    elasticsearch:
      nodeCount: {{ clo_nodes | default (1) }} 
{% if clo_node_selector is defined %}
      nodeSelector: 
        {{ clo_node_selector }}
{% endif %}
      storage:
        storageClassName: {{ clo_sc_name | default('gp2') }}
        size: 200G
      redundancyPolicy: "{{ clo_redundancy | default ('ZeroRedundancy') }}"
      resources: 
        limits:
          cpu: "3000m"
          memory: "4Gi"
        requests:
          cpu: "1000m"
          memory: "1Gi"
  visualization:
    type: "kibana"  
    kibana:
      replicas: 1
{% if clo_node_selector is defined %}
      nodeSelector: 
        {{ clo_node_selector }}
{% endif %}
  curation:
    type: "curator"  
    curator:
      schedule: "30 3 * * *"
{% if clo_node_selector is defined %}
      nodeSelector:
        {{ clo_node_selector }}
{% endif %}
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}
