apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat 
  annotations:
    openshift.io/node-selector: "{{ clo_node_selector }}"
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
