apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/mco-built-in: ""
  name: {{ infra_role }}
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/pool_{{ infra_role }}: 'true'
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/{{ infra_role }}: ""
  paused: false
