apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
      volumeClaimTemplate:
        metadata:
          name: prompvc
        spec:
          storageClassName: {{ clmon_sc_name }}
          resources:
            requests:
              storage: {{ clmon_prom_pvc_size}}
    alertmanagerMain:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      volumeClaimTemplate:
        metadata:
          name: alertmanpvc
        spec:
          storageClassName: {{ clmon_sc_name }}
          resources:
            requests:
              storage: {{ clmon_am_pvc_size }}
    prometheusOperator:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
    kubeStateMetrics:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
    grafana:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
    telemeterClient:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
    k8sPrometheusAdapter:
{% if clmon_node_selector is defined %}
      nodeSelector:
        {{ clmon_node_selector }}
{% endif %}
