apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    machineconfiguration.openshift.io/mco-built-in: ""
  name: infra
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/pool_infra: 'true'
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/infra: ""
  paused: false
